In [1]:
import numpy as np

In [3]:
# misalnya kita punya list isi panjang, dan list isi lebar untuk ukuran kertas kita
list_lebar = [50, 30, 25, 70]
list_panjang = [50, 37.5, 100, 35]

# luas masing2 kertas kita berapa?
area = list_lebar * list_panjang
print(area)

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
# kita gunakan tipe data numpy, yaitu numpy array
# semua data yang ada di dalam numpy array adalah numerik

arr_lebar = np.array(list_lebar)
arr_panjang = np.array(list_panjang)

area = arr_lebar * arr_panjang
print(area)

[2500. 1125. 2500. 2450.]


# Numpy
module/package numerical python.

Di dalam numpy ini ada tipe data baru: numpy array, numpy.ndarray
- CRUD, create read update delete, membuat, membaca, mengupdate, mengahapus numpy array

Ada banyak built-in function untuk memproses data sebuah numpy array.
- mean, std dev, variance, min, max, dll
- banyak juga function untuk membuat dan mengubah numpy array

Ada beberapa peraturan dalam pembuatan sebuah numpy array.

## Create
membuat numpy array dengan cara:
1. np.array(list_angka)
2. np.ones(ukuran_arr), np.zeros(ukuran_arr)
3. np.random.random(ukuran_arr)
4. np.arange(angka awal, angka akhir, increment) -- cara pakenya sama seperti range()

In [7]:
# cara membuat numpy array
# 1. convert list atau tuple menjadi numpy array

print(list_lebar, type(list_lebar))

arr = np.array(list_lebar)
print(arr, type(arr))

[50, 30, 25, 70] <class 'list'>
[50 30 25 70] <class 'numpy.ndarray'>


In [8]:

arr = np.array([-2,56.45,3])
print(arr, type(arr))

[-2.   56.45  3.  ] <class 'numpy.ndarray'>


In [9]:

arr = np.array([[1],[2],[3]])
print(arr, type(arr))

[[1]
 [2]
 [3]] <class 'numpy.ndarray'>


In [10]:
# 2.a. generate numpy array yang isinya angka 0 semua

arr0 = np.zeros(10)
print(arr0, type(arr0))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] <class 'numpy.ndarray'>


In [15]:
arr0 = np.zeros((2,4))
print(arr0, type(arr0))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]] <class 'numpy.ndarray'>


In [32]:
arr0 + 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [12]:
# 2.b. generate numpy array yang isinya angka 1 semua

arr1 = np.ones(3)
print(arr1, type(arr1))

[1. 1. 1.] <class 'numpy.ndarray'>


In [13]:

arr1 = np.ones((3, 5))
print(arr1, type(arr1))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] <class 'numpy.ndarray'>


In [33]:
arr1 * 7

array([[7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7.]])

In [17]:
# 3. menggunakan np.random.random untuk membuat numpy array isi angka random antara 0-1

arr_random = np.random.random(10)
print(arr_random)

[0.80990534 0.42882813 0.39206056 0.6090659  0.58353882 0.75447719
 0.99144489 0.16083608 0.63770226 0.90991784]


In [26]:
# dengan tambah teknik numpy yang namanya "broadcasting"
# dan fungsi astype() untuk mengubah tipe data
# kita bisa bikin numpy array berisi angka random antara 1-10


arr10 = (np.random.random(10) * 10 + 1).astype(int)
print(arr10)

[10 10  2 10  3  5  6  7  5  5]


In [27]:
# kita mau buat data hasil lempar dadu sebanyak 100 kali
arr_dadu = (np.random.random(100) * 6 + 1).astype(int)
print(arr_dadu)

[4 5 4 4 1 4 6 2 1 6 4 1 3 4 4 2 6 3 1 3 2 5 5 3 6 1 5 3 6 5 1 1 5 1 5 3 4
 4 2 2 1 2 5 1 5 4 6 4 4 2 3 2 2 3 6 4 1 6 2 4 5 2 1 5 3 4 6 2 5 2 1 4 2 1
 2 3 4 6 1 2 3 2 1 3 4 4 6 4 1 1 5 2 3 6 5 6 5 3 1 3]


In [18]:

arr_random = np.random.random((3,2))
print(arr_random)

[[0.03860634 0.8834084 ]
 [0.33657863 0.434111  ]
 [0.60267306 0.51205878]]


In [19]:
# 4. numpy array isi angka urut
# mirip range() yang digunakan untuk membuat angka urut
arr_urut = np.arange(5)
print(arr_urut)

[0 1 2 3 4]


In [22]:

arr_urut = np.arange(5,10)
print(arr_urut)

[5 6 7 8 9]


In [23]:

arr_urut = np.arange(5,100,20)
print(arr_urut)

[ 5 25 45 65 85]


# broadcasting
sebuah numpy array bisa melakukan aritmatik dengan sebuah angka numerik.

array * / + - sebuah angka

In [30]:
hasil = np.array([4,5,6]) * 10
print(hasil)

[40 50 60]


In [31]:
hasil = np.array([4,5,6]) * 10 / 3 + 3 -100
print(hasil)

[-83.66666667 -80.33333333 -77.        ]


## update
kita belum ke cara read numpy array nya, kita cobain bbrp teknik update numpy array dulu
- add/ np.append
- remove/ np.delete
- np.sort

In [34]:
a = np.array([2,3,4])
print(a, type(a))

[2 3 4] <class 'numpy.ndarray'>


In [38]:
# add/ append
b = np.append(a, 5)
print(b)
print(a, "array awal nya tidak diubah")

[2 3 4 5]
[2 3 4] array awal nya tidak diubah


In [39]:
b = np.append(a, [5,6,7])
print(b)

[2 3 4 5 6 7]


In [43]:
b = np.append(a, [10,14,30])
print(b)

[ 2  3  4 10 14 30]


In [45]:
# remove/ delete
c = np.delete(b, 2)
print(c)
print(b, "tidak mengubah data awal")

[ 2  3 10 14 30]
[ 2  3  4 10 14 30] tidak mengubah data awal


In [48]:
# sort
a = (np.random.random(8)*100-50).astype(int)/10
print(a)

[-0.5  2.7 -2.8  0.9  4.4  3.9  4.3 -1.2]


In [49]:
a_sorted = np.sort(a)
print(a_sorted)

[-2.8 -1.2 -0.5  0.9  2.7  3.9  4.3  4.4]


## Read
read properti sebuah numpy array nya seperti ukuran, dimensi, ada berapa angka di dalam sebuah numpy array:
- arr.shape --> bentuk
- arr.size --> jumlah angka yang ada di arr
- arr.ndim --> dimensi

In [53]:
print(a_sorted)
print("shape", a_sorted.shape)
print("size", a_sorted.size)
print("dimensi", a_sorted.ndim)

[-2.8 -1.2 -0.5  0.9  2.7  3.9  4.3  4.4]
shape (8,)
size 8
dimensi 1


In [54]:
a = np.ones((5,3))
print(a)
print("shape", a.shape)
print("size", a.size)
print("dimensi", a.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
shape (5, 3)
size 15
dimensi 2


In [58]:
a * 3 + 5

array([[8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.],
       [8., 8., 8.]])

In [56]:
b = np.ones((5,3,2))
print(b)
print("shape", b.shape)
print("size", b.size)
print("dimensi", b.ndim)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
shape (5, 3, 2)
size 30
dimensi 3


In [63]:
# antara 2 array kalau ukuran sama, bisa di aritmatik juga
a = np.ones((3,2)) * 5
b = np.ones((3,1)) * 3

print(a)
print(b)
print(a + b)

[[5. 5.]
 [5. 5.]
 [5. 5.]]
[[3.]
 [3.]
 [3.]]
[[8. 8.]
 [8. 8.]
 [8. 8.]]


### reshape
setelah memahami shape, atau bentuk sebuah numpy array

kita belajar tentang reshape, mengubah shape sebuah numpy array

In [71]:
a = np.arange(6).reshape((3,2))
print(a)
print(a.shape)

[[0 1]
 [2 3]
 [4 5]]
(3, 2)


In [72]:
b = a.reshape(6)
print(b)
print(b.shape)

[0 1 2 3 4 5]
(6,)


In [73]:
b = a.reshape((2,3))
print(b)
print(b.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


# aritmatik di numpy array
antara dua numpy array, atau antara 1 numpy array dan sebuah angka, bisa kita lakukan proses aritmatik:
- \+ \- \* \/ \% \**
- np.sqrt (akar)

In [79]:
a = np.arange(5,11).reshape((2,3))
print(a)

b = np.arange(-10,8,3).reshape(2,3)
print(b)

[[ 5  6  7]
 [ 8  9 10]]
[[-10  -7  -4]
 [ -1   2   5]]


In [81]:
print(a + b)

[[-5 -1  3]
 [ 7 11 15]]


In [82]:
print(a - b)

[[15 13 11]
 [ 9  7  5]]


In [83]:
print(a * b)

[[-50 -42 -28]
 [ -8  18  50]]


In [84]:
print(a / b)

[[-0.5        -0.85714286 -1.75      ]
 [-8.          4.5         2.        ]]


In [85]:
print(a % b)

[[-5 -1 -1]
 [ 0  1  0]]


In [87]:
print(b ** a)

[[-100000  117649  -16384]
 [      1     512 9765625]]


In [88]:
# dicampur antara array dan angka juga boleh
print(a + b - 10 * 3)

[[-35 -31 -27]
 [-23 -19 -15]]


In [89]:
c = a + b - 10 * 3

# read
masih di read, kita belajar teknik membaca 1 atau banyak angka dalam sebuah numpy array
- indexing, membaca 1 angka
- slicing, membaca banyak angka

In [90]:
print(c)

[[-35 -31 -27]
 [-23 -19 -15]]


In [91]:
# indexing, baca angka di baris pertama, kolom pertama
# note, angka index dimulai dari 0
c[0,0]

# posisi dimensi 1, baris nya, adalah index 0
# posisi dimensi 2, kolom nya, adalah index 0

-35

In [92]:
# indexing, ambil angka di baris kedua, kolom terakhir
# baris kedua, index 1. kolom terakhir, index -1.
c[1, -1]

-15

In [93]:
print(c)

[[-35 -31 -27]
 [-23 -19 -15]]


In [94]:
# slicing, kita mau ambil semua angka di kolom kedua
# semua baris, all index untuk baris
# kolom kedua, index 1
c[:, 1]

array([-31, -19])

In [95]:
# slicing, kita mau ambil semua angka di kolom kedua dan ketiga
# semua baris, all index untuk baris
# kolom kedua dan ketiga, index 1 dan index 2, 1:3 (kolom 1 sampai 2)
c[:, 1:3]

array([[-31, -27],
       [-19, -15]])

In [96]:
# karena kebetulan kolom ketiga adalah kolom terakhir juga, kita juga bisa tulis seperti berikut
# dari kolom kedua sampai kolom terakhir, 1:
c[:, 1:]

array([[-31, -27],
       [-19, -15]])

In [101]:
# kita bisa edit sebagian array kita
c[:, 1]

array([-31, -19])

In [103]:
# misalkan mau nambah 100 ke kolom kedua
# note: karena kita menimpa data awal c[:, 1] pastikan code ini hanya di run 1x

c[:, 1] = c[:, 1] + 100

print(c)

[[-35 169 -27]
 [-23 181 -15]]


## Query
mengambil angka angka tertentu dari sebuah numpy array, menggunakan kondisi

In [104]:
print(c)

[[-35 169 -27]
 [-23 181 -15]]


In [105]:
# ambil angka positif saja, >= 0
c >= 0

# array boolean seperti ini bisa kita gunakan sebagai index

array([[False,  True, False],
       [False,  True, False]])

In [106]:
kondisi = (c >= 0)

c[kondisi]

array([169, 181])

In [107]:
# kondisinya tidak dimasukkan ke variable juga boleh
c[(c >= 0)]

array([169, 181])

In [122]:
# contoh, ada 3 orang yang lempar dadu 100x masing2
# data jadi 3 baris 100 kolom hasil angka 1-6

arr_dadu = (np.random.random(300) * 6 + 1).astype(int)
arr_dadu = arr_dadu.reshape((3, 100))
arr_dadu

array([[6, 1, 3, 3, 3, 5, 2, 1, 5, 1, 6, 1, 5, 3, 6, 4, 3, 4, 2, 6, 5, 1,
        5, 6, 4, 2, 4, 2, 5, 1, 5, 6, 2, 6, 1, 2, 3, 6, 5, 1, 6, 6, 2, 6,
        5, 5, 2, 2, 1, 6, 4, 6, 3, 2, 1, 6, 2, 3, 4, 4, 2, 2, 6, 5, 2, 5,
        1, 5, 6, 4, 3, 6, 6, 5, 3, 4, 3, 1, 6, 1, 6, 4, 2, 3, 1, 3, 2, 6,
        5, 6, 5, 6, 2, 1, 5, 5, 1, 6, 6, 2],
       [1, 1, 5, 2, 4, 1, 3, 1, 4, 1, 2, 1, 6, 3, 2, 3, 4, 1, 1, 6, 6, 1,
        1, 1, 5, 3, 1, 3, 1, 3, 2, 3, 3, 2, 5, 4, 2, 2, 6, 5, 5, 6, 5, 5,
        2, 4, 4, 5, 3, 1, 3, 3, 2, 5, 3, 6, 6, 4, 6, 4, 3, 1, 5, 3, 3, 3,
        3, 5, 6, 5, 4, 5, 6, 5, 4, 1, 5, 4, 5, 5, 3, 3, 2, 6, 5, 6, 1, 6,
        1, 2, 5, 4, 6, 5, 3, 6, 1, 2, 2, 6],
       [4, 3, 3, 5, 4, 4, 5, 3, 2, 5, 5, 2, 3, 4, 2, 2, 1, 3, 6, 6, 3, 3,
        2, 3, 5, 5, 2, 2, 2, 2, 2, 1, 5, 1, 5, 2, 5, 5, 2, 3, 3, 4, 6, 3,
        2, 1, 2, 1, 5, 3, 2, 3, 3, 3, 4, 5, 1, 5, 4, 2, 3, 1, 2, 4, 5, 6,
        1, 1, 3, 6, 2, 6, 1, 2, 2, 4, 4, 2, 1, 3, 5, 4, 4, 3, 1, 3, 1, 2,
        4, 2, 6, 5, 5,

In [123]:
# yang nilai nya 6 ada berapa kali?
# operator komparator > < >= <= == !=
kondisi = (arr_dadu == 6)
print(arr_dadu[kondisi]) # memastikan array baru isinya 6 semua
print(arr_dadu[kondisi].size) # menghitung ukuran array baru

# kita mendapat hasil kalau ada 48 angka di array yang kondisinya angka harus "6"

[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6]
48


In [124]:
# masing-masing orang tersebut ada berapa kali lempar angka 6?
# array termasuk koleksi, kita minta bantuan loop for

hasil = []
for row in arr_dadu:
    # print(row)
    # print(row[row==6])
    hasil.append(row[row==6].size)

print("orang pertama", hasil[0], "kali dapat angka 6")
print("orang kedua", hasil[1], "kali dapat angka 6")
print("orang ketiga", hasil[2], "kali dapat angka 6")

orang pertama 25 kali dapat angka 6
orang kedua 16 kali dapat angka 6
orang ketiga 7 kali dapat angka 6


# stack, split, copy
ada beberapa function bawaan numpy yang bisa kita gunakan untuk:
- stack -- menggabungkan beberapa numpy array jadi satu
    - hstack -- gabungin kiri ke kanan, horizontal
    - vstack -- gabungin atas ke bawah, vertical
- split -- memisahkan sebuah numpy array menjadi beberapa bagian yang sama besarnya
    - hsplit -- horizontal split
    - vsplit -- vertical split
- copy -- membuat copy dari numpy array
    - view -- shallow copy, copyan secara reference, kayak kasih nickname, 1 diubah, kopiannya ikut berubah juga
    - copy -- deep copy, copyan secara value, kayak membuat array baru yang isinya sama

In [125]:
print(a)
print(b)

[[ 5  6  7]
 [ 8  9 10]]
[[-10  -7  -4]
 [ -1   2   5]]


In [127]:
# hstack
np.hstack((a,b))

array([[  5,   6,   7, -10,  -7,  -4],
       [  8,   9,  10,  -1,   2,   5]])

In [128]:
c = np.array([[10],[20]])
print(c)

[[10]
 [20]]


In [130]:
# tumpukin bbrp kali juga boleh
# hstack --> jumlah baris harus sama, kolom beda gpp
np.hstack((a,b,c,c,c,c,c))

array([[  5,   6,   7, -10,  -7,  -4,  10,  10,  10,  10,  10],
       [  8,   9,  10,  -1,   2,   5,  20,  20,  20,  20,  20]])

In [131]:
# vstack
np.vstack((a,b))

array([[  5,   6,   7],
       [  8,   9,  10],
       [-10,  -7,  -4],
       [ -1,   2,   5]])

In [132]:
c = np.array([[10,20,30]])
print(c)

[[10 20 30]]


In [135]:
# tumpukin bbrp kali juga boleh
# vstack --> jumlah kolom harus sama, baris beda gpp
np.vstack((c,a,b,c))

array([[ 10,  20,  30],
       [  5,   6,   7],
       [  8,   9,  10],
       [-10,  -7,  -4],
       [ -1,   2,   5],
       [ 10,  20,  30]])

numpy array harus dibuat dengan bentuk yang full, yang pas, tidak bolong bolong. jumlah kolom di setiap baris harus sama.

In [136]:
np.array([[1],[2,3],[4,5,6]])

C:\Users\stefa\AppData\Local\Temp\ipykernel_17324\2261630847.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1],[2,3],[4,5,6]])


array([list([1]), list([2, 3]), list([4, 5, 6])], dtype=object)

In [138]:
# kalau mau bolong bolong datanya, pastika diisi "np.nan" nan atau missing value
np.array([[1,np.nan,np.nan],[2,3,np.nan],[4,5,6]])

array([[ 1., nan, nan],
       [ 2.,  3., nan],
       [ 4.,  5.,  6.]])

In [140]:


d = np.vstack((a,b,c,c))
print(d.shape)
print(d)

(6, 3)
[[  5   6   7]
 [  8   9  10]
 [-10  -7  -4]
 [ -1   2   5]
 [ 10  20  30]
 [ 10  20  30]]


In [141]:
# vsplit, split array nya secara vertical
np.vsplit(d, 3)

# 6 dibagi 3 dapat 2 baris per bagian yang dipisah

[array([[ 5,  6,  7],
        [ 8,  9, 10]]),
 array([[-10,  -7,  -4],
        [ -1,   2,   5]]),
 array([[10, 20, 30],
        [10, 20, 30]])]

In [142]:
# kalau baginya gak pas, dia gk mau
np.vsplit(d, 4)

ValueError: array split does not result in an equal division

In [143]:
np.vsplit(d, 2)

[array([[  5,   6,   7],
        [  8,   9,  10],
        [-10,  -7,  -4]]),
 array([[-1,  2,  5],
        [10, 20, 30],
        [10, 20, 30]])]

In [144]:
np.vsplit(d, 3)

[array([[ 5,  6,  7],
        [ 8,  9, 10]]),
 array([[-10,  -7,  -4],
        [ -1,   2,   5]]),
 array([[10, 20, 30],
        [10, 20, 30]])]

In [145]:
np.vsplit(d, 6)

[array([[5, 6, 7]]),
 array([[ 8,  9, 10]]),
 array([[-10,  -7,  -4]]),
 array([[-1,  2,  5]]),
 array([[10, 20, 30]]),
 array([[10, 20, 30]])]

In [146]:
# kisa bisa langsung masukin setiap bagian ke variable
d1,d2,d3 = np.vsplit(d, 3)

print(d1)

[[ 5  6  7]
 [ 8  9 10]]


In [147]:
# hsplit
print(a)

[[ 5  6  7]
 [ 8  9 10]]


In [148]:
a1,a2,a3 = np.hsplit(a,3)

print(a1)

[[5]
 [8]]


In [149]:
print(a2)

[[6]
 [9]]


In [150]:
print(a3)

[[ 7]
 [10]]


In [153]:
# view dan copy
# view, shallow copy, copy by reference, kasih nama lain ke data yang sama
print(a)

a_view = a.view()
print(a_view)

a_copy = a.copy()
print(a_copy)

[[ 5  6  7]
 [ 8  9 10]]
[[ 5  6  7]
 [ 8  9 10]]
[[ 5  6  7]
 [ 8  9 10]]


In [154]:
# kalau kita ganti a, a_view ikut berubah, a_copy tidak
a[0,0] = 100
print(a)
print(a_view)

print(a_copy)

[[100   6   7]
 [  8   9  10]]
[[100   6   7]
 [  8   9  10]]
[[ 5  6  7]
 [ 8  9 10]]


In [156]:
# kalau kita ganti a_view, a ikut berubah, a_copy tidak
a_view[0,0] = -5
print(a)
print(a_view)

print(a_copy)

[[-5  6  7]
 [ 8  9 10]]
[[-5  6  7]
 [ 8  9 10]]
[[ 5  6  7]
 [ 8  9 10]]


In [157]:
arr = np.array([10,20,30])

v = arr.view()

print(arr)

[10 20 30]


In [159]:
# ubah arr, v ikut2an berubah
# ubah v, arr ikut2an berubah
v[0] = -10

print(arr)

[-10  20  30]


In [160]:
# lebih umum kita pakai copy, hasil copynya tidak berubah ikut2an data awal
print(arr)

[-10  20  30]


In [161]:
c = arr.copy()

arr[0] = 100

print(c)

[-10  20  30]


In [162]:
print(arr)

[100  20  30]


menggunakan view, data hasil kopi dan data awal masih terhubung

menggunakan copy, data kasil kopi dan data awal sudah tidak punya hubungan

In [167]:
# delete numpy array
# cara umumnya, kita set ke numpy array kosong, atau ke None

a = np.array([])
print(a, type(a))
print(bool(a.size))

[] <class 'numpy.ndarray'>
False


# Aggregation
menggunakan teknik dari numpy untuk menghitung angka agregasi (sum, mean, min, max, dll)

In [168]:
# ambil data lempar dadu tadi
print(arr_dadu)

array([[6, 1, 3, 3, 3, 5, 2, 1, 5, 1, 6, 1, 5, 3, 6, 4, 3, 4, 2, 6, 5, 1,
        5, 6, 4, 2, 4, 2, 5, 1, 5, 6, 2, 6, 1, 2, 3, 6, 5, 1, 6, 6, 2, 6,
        5, 5, 2, 2, 1, 6, 4, 6, 3, 2, 1, 6, 2, 3, 4, 4, 2, 2, 6, 5, 2, 5,
        1, 5, 6, 4, 3, 6, 6, 5, 3, 4, 3, 1, 6, 1, 6, 4, 2, 3, 1, 3, 2, 6,
        5, 6, 5, 6, 2, 1, 5, 5, 1, 6, 6, 2],
       [1, 1, 5, 2, 4, 1, 3, 1, 4, 1, 2, 1, 6, 3, 2, 3, 4, 1, 1, 6, 6, 1,
        1, 1, 5, 3, 1, 3, 1, 3, 2, 3, 3, 2, 5, 4, 2, 2, 6, 5, 5, 6, 5, 5,
        2, 4, 4, 5, 3, 1, 3, 3, 2, 5, 3, 6, 6, 4, 6, 4, 3, 1, 5, 3, 3, 3,
        3, 5, 6, 5, 4, 5, 6, 5, 4, 1, 5, 4, 5, 5, 3, 3, 2, 6, 5, 6, 1, 6,
        1, 2, 5, 4, 6, 5, 3, 6, 1, 2, 2, 6],
       [4, 3, 3, 5, 4, 4, 5, 3, 2, 5, 5, 2, 3, 4, 2, 2, 1, 3, 6, 6, 3, 3,
        2, 3, 5, 5, 2, 2, 2, 2, 2, 1, 5, 1, 5, 2, 5, 5, 2, 3, 3, 4, 6, 3,
        2, 1, 2, 1, 5, 3, 2, 3, 3, 3, 4, 5, 1, 5, 4, 2, 3, 1, 2, 4, 5, 6,
        1, 1, 3, 6, 2, 6, 1, 2, 2, 4, 4, 2, 1, 3, 5, 4, 4, 3, 1, 3, 1, 2,
        4, 2, 6, 5, 5,

In [170]:
# anggap kita mau cari tau: 
# - total nilai yang didapat
# - total nilai yang didapat per orang
# - selain total, rata2, min, max juga bisa

print("total nilai yang didapat")
arr_dadu.sum()

total nilai yang didapat


1039

In [172]:
print("total nilai yang didapat per orang")
arr_dadu.sum(axis=1)

total nilai yang didapat per orang


array([371, 349, 319])

In [173]:
print("rata2, min, max nilai yang didapat")
print(arr_dadu.mean(), arr_dadu.min(), arr_dadu.max())

rata2, min, max nilai yang didapat
3.4633333333333334 1 6


In [174]:
print("rata2, min, max nilai yang didapat per orang")
print(arr_dadu.mean(axis=1), arr_dadu.min(axis=1), arr_dadu.max(axis=1))

rata2, min, max nilai yang didapat per orang
[3.71 3.49 3.19] [1 1 1] [6 6 6]


# Matrix

"vector" -- numpy array 2 dimensi yang cuma punya 1 baris, atau cuma punya 1 kolom

"matrix" -- numpy array 2 dimensi

 matrix dot product

In [178]:
a = np.array([[1,2,3]])
b = np.array([[1,2],[3,4],[5,6]])

print("vector - cuma punya 1 baris, atau cuma punya 1 kolom")
print(a, a.shape, a.ndim)
print()
print("matrix")
print(b, b.shape, b.ndim)

vector
[1 2 3] (3,) 1

matrix
[[1 2]
 [3 4]
 [5 6]] (3, 2) 2


# Dot Product
web ini ada gambar step by step cara menghitung dot product https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [179]:
profit = np.array([[2500,3000]])

jumlah = np.array([[5,10,7],[12,11,20]])

print(profit)
print(jumlah)

[[2500 3000]]
[[ 5 10  7]
 [12 11 20]]


In [180]:
# hitung dot product
profit.dot(jumlah)

array([[48500, 58000, 77500]])

hasil hitung profit senin, selasa, rabu adalah 48500, 58000, 77500.

senin - 48500, selasa - 58000, rabu - 77500

In [181]:
# kalau mau total profit keseluruhan
profit.dot(jumlah).sum()

184000

# Transpose
yang tadinya teman sekolom jadi teman sebaris, vice versa

In [182]:
print(jumlah)

[[ 5 10  7]
 [12 11 20]]


In [185]:
# kalau pakai reshape, datanya melupakan temannya
jumlah.reshape((3,2))

array([[ 5, 10],
       [ 7, 12],
       [11, 20]])

reshape hanya memastikan bentuk ukuran berubah, angka2nya sendiri dia isi urut aja kiri ke kanan, atas ke bawah

In [186]:
# untuk transpose, dia memastikan yang tadinya sebaris sekarang jadi sekolom
jumlah.T

array([[ 5, 12],
       [10, 11],
       [ 7, 20]])

untuk data yang ada hubungannya, sebaris data ada hubungan, jika bentuk mau diubah kita pakai transpose bukan reshape